# Generated by Django 4.2.6 on 2023-11-15 16:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_postmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
