# Generated by Django 4.2.6 on 2023-11-15 16:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_postmodel_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="comment",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
