# Generated by Django 4.2.6 on 2023-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_commentmodel_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/post-thumbnail/"
            ),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="comment",
            field=models.TextField(),
        ),
    ]
