# Generated by Django 4.2.6 on 2023-12-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usermodel_image_prof"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="tmp_token",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="tmp_token_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
